---
- name: Install apt packages
  sudo: yes
  apt: pkg={{ item }} state=installed
  with_items:
    - nodejs
    - nodejs-legacy
    - npm
    - git
    - ruby-compass  # wymagane przez grunt'a

- name: Install nodejs modules
  sudo: yes
  npm: name={{ item }}  global=yes
  with_items:
    - grunt
    - grunt-cli
    - bower

- name: Link application sources
  command: /bin/ln -s /vagrant /home/vagrant/src creates=/home/vagrant/src
